# Generated by Django 5.1.6 on 2025-02-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Untitled Event", max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(default="To be announced", max_length=255),
                ),
                ("category", models.CharField(default="General", max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        default="event_images/default.jpg", upload_to="event_images/"
                    ),
                ),
            ],
        ),
    ]
