# Generated by Django 5.1.6 on 2025-02-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="No description available.")),
                ("schedule", models.TextField(default="Schedule to be announced.")),
                ("speakers", models.TextField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("sponsors", models.TextField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=100)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
