# Generated by Django 5.1.6 on 2025-02-20 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdetail",
            name="agenda",
        ),
        migrations.RemoveField(
            model_name="eventdetail",
            name="speakers",
        ),
        migrations.RemoveField(
            model_name="eventdetail",
            name="sponsors",
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="countdown_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="google_maps_embed",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="reviews_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="social_media_links",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="ticket_types",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name="EventAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.TimeField()),
                ("activity", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="speakers/"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sponsorship_level",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Bronze", "Bronze"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
