
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ticketease_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load environment variables from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: ticketease_django
    restart: always
    depends_on:
      - db  # Ensure the database starts first
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --noinput &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:

