
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ticketease_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load environment variables from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

