# Generated by Django 5.1.6 on 2025-02-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_poster_url_movie_genre_movie_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Venue Name')),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['datetime'], 'verbose_name': 'Showtime', 'verbose_name_plural': 'Showtimes'},
        ),
        migrations.AlterField(
            model_name='showtime',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Showtime Date & Time'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.venue', verbose_name='Venue'),
        ),
    ]
