# Generated by Django 5.1.6 on 2025-02-19 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_delete_showtime_delete_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.PositiveIntegerField(verbose_name='Screen Number')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Venue Name')),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Showtime Date & Time')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showtimes', to='movies.screen', verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Showtime',
                'verbose_name_plural': 'Showtimes',
                'ordering': ['datetime'],
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('venue', 'screen_number')},
        ),
    ]
