# Generated by Django 5.1.6 on 2025-02-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_screen_venue_showtime_screen_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('seat_class', models.CharField(choices=[('Diamond', 'Diamond Class'), ('Gold', 'Gold Class'), ('Silver', 'Silver Class')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_booked', models.BooleanField(default=False)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.showtime')),
            ],
        ),
    ]
