# Generated by Django 5.1.6 on 2025-02-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="seat_class",
            field=models.CharField(
                choices=[("Diamond", "Diamond Class"), ("Gold", "Gold Class")],
                max_length=10,
            ),
        ),
    ]
