# Generated by Django 5.1.6 on 2025-03-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_seat_seat_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
